services:
  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: election-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - election-network
    restart: unless-stopped

  # PHP-FPM Application Server
  app:
    build:
      context: .
      dockerfile: DockerFile
    container_name: election-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    depends_on:
      - db
    networks:
      - election-network
    restart: unless-stopped

  # SQLite Database (via volume)
  db:
    image: alpine:latest
    container_name: election-db
    volumes:
      - ./database:/database
    networks:
      - election-network
    restart: unless-stopped

networks:
  election-network:
    driver: bridge
